spring:
    config:
        # Import actual values over the top of "invalid-placeholder"
        import: secrets.yaml
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://invalid-placeholder?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
        username: invalid-placeholder
        password: invalid-placeholder
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    data:
        rest:
            # Set base path for automagic Spring REST APIs
            base-path: /api
okta:
    oauth2:
        client-id: invalid-placeholder
        issuer: https://invalid-placeholder/oauth2/default
